### ISSUE TITLE
Variable Y level stop

### ISSUE THREAD

**Issue by ProgrammerDan** [DevotedMC/Orebfuscator#9]
for specific obfuscation (like signs)

Not sure how to express this, besides a "wish" that signs in cities could avoid obfuscation.

**Comment by Aleksey-Terzi** [comment]
I've mostly done refactoring for config file.  

The next step will be to allow hierarchical definition for worlds to allow per world config, something like:

```
...  
Worlds:  
  World:
    Types: [Default]
    Enabled: true
  World:
    Types: [Normal, End]
    ObfuscateBlocks:
      - GOLD_ORE
      - IRON_ORE
      - COAL_ORE
      - LAPIS_ORE
      - CHEST
      - DIAMOND_ORE
      - REDSTONE_ORE
      - GLOWING_REDSTONE_ORE
      - EMERALD_ORE
      - ENDER_CHEST
  World:
    Types: [Nether]
    ObfuscateBlocks:
      - NETHERRACK
      - QUARTZ_ORE
  World:
    Names: [FantasyWorld, TradeCenter]
    Enabled: false
...
```

After that I will try to implement hierarchical ProximityHider which allows to specify different settings for different block types (and therefore specify ProximityHiderEnd for signs)
But not yet sure how this will implemented and work.

According to signs in the cities we could probably use here another way (because of I'm not sure that binding to Y would be good):

1) In the scope of "per world config" task - I will implement OrebfuscatorManager class which is providing different helper functions like - what block to obfuscate and etc.

2) Based on this we could implement plugin (or embed function in one of existing only-Devoted plugins) which is overriding OrebfuscatorManager

3) In our DevotedOrebfuscatorManager class we could allow to obfuscate only signs we want

4) In our plugin introduce new function which allows by left clicking with stick to change sign visibility for orebfuscator

5) Internally list of non-obfuscate signs will be saved in hashtable, externally in list of "transaction" files (one file per 10 min) - each time when sign state is changed - change action will be saved to the file, On server start - all files will be reorganized to one file.

Probably bad idea which is making life harder :)

Please let me know your opinion.

**Comment by Aleksey-Terzi** [comment]
New feature (variable Y level) is implemented and changes pushed.

How to apply new update:

1) Run server with new plugin - it will convert config file to new format

2) Add to config file to ProximityHider section for DEFAULT world type subsection like following:

```
ProximityHiderBlockSettings:
  SIGN_POST:
    Y: 95
    ObfuscateAboveY: false
  WALL_SIGN:
    Y: 95
    ObfuscateAboveY: false
```

More details on new config file format is here: https://github.com/lishid/Orebfuscator/wiki/Configuration-File-(4.1.14)
